import { Hurricane } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
const font = Hurricane({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
